(define (problem viatges) (:domain trobaviatges)
  (:objects
    C1 C2 Co
    A1-1 A1-2 A2-1 A2-2
    V1-2 V2-1 Vo-1 Vo-2 V1-o V2-o
  )

  (:init
    (Ciutat Co)
    (Ciutat C1)
    (Ciutat C2)
    (Allotjament A1-1)
    (Allotjament A1-2)
    (Allotjament A2-1)
    (Allotjament A2-2)
    (Vol Vo-1)
    (Vol Vo-2)
    (Vol V1-o)
    (Vol V2-o)
    (Vol V1-2)
    (Vol V2-1)
    (Allotjamentde A1-1 C1)
    (Allotjamentde A1-2 C1)
    (Allotjamentde A2-1 C2) 
    (Allotjamentde A2-2 C2)
    (Vuelode V1-2 C1 C2)
    (Vuelode V2-1 C2 C1)
    (Vuelode Vo-2 Co C2)
    (Vuelode Vo-1 Co C1)
    (Vuelode V1-o C1 Co)
    (Vuelode V2-o C2 Co)
    (=(diesperciutat C1)0)
    (=(diesperciutat C2)0)
    (= (visitades) 0 )
    (= (minim-ciu) 1)
    (= (minim-d-c) 2)
    (= (maxim-d-c) 4)
    (= (minim-d) 3)
    (= (diastotal) 0)
    (= (interestotal)0)
    (=(interes C1)2)
    (=(interes C2)3)
    (en Co)
  )
  (:goal (and   
      (>= (visitades) (minim-ciu))
      (>= (diastotal) (minim-d))
      (en Co)
    )
  )
  (:metric minimize (interestotal))
) 